include(${CMAKE_SOURCE_DIR}/cmake/protoc_generate_obj.cmake)

protobuf_generate_obj(PROTO_PATH calculators/core OBJ_NAME flow_limiter_calculator)
protobuf_generate_obj(PROTO_PATH calculators/core OBJ_NAME gate_calculator)
protobuf_generate_obj(PROTO_PATH calculators/core OBJ_NAME constant_side_packet_calculator)
protobuf_generate_obj(PROTO_PATH calculators/core OBJ_NAME split_vector_calculator)
protobuf_generate_obj(PROTO_PATH calculators/core OBJ_NAME clip_vector_size_calculator)
