include(${CMAKE_SOURCE_DIR}/cmake/protoc_generate_obj.cmake)

protobuf_generate_obj(PROTO_PATH framework OBJ_NAME calculator_options DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME mediapipe_options DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME packet_factory DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME packet_generator DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME status_handler DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME stream_handler DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME thread_pool_executor)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME calculator DESCRIPTORS)
protobuf_generate_obj(PROTO_PATH framework OBJ_NAME calculator_profile)

include(${CMAKE_CURRENT_LIST_DIR}/deps/protobuf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/tool/protobuf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/formats/object_detection/protobuf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/formats/annotation/protobuf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/formats/protobuf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/stream_handler/protobuf.cmake)
