include(${CMAKE_SOURCE_DIR}/cmake/protoc_generate_obj.cmake)

PROTOBUF_GENERATE_OBJ_WITH_DEPS(tflite.ssd_anchors_calculator "framework.calculator;framework.calculator_options;object_detection.anchor")
PROTOBUF_GENERATE_OBJ_WITH_DEPS(tflite.tflite_custom_op_resolver_calculator "framework.calculator;framework.calculator_options")
