find_package(Protobuf 3.19 CONFIG)
if(Protobuf_FOUND)
    message("Protobuf FOUND ${Protobuf_VERSION}")
else()
    include(protobuf)
endif()
if(Protobuf_POPULATED)
    set(Protobuf_LIBRARIES protobuf CACHE STRING "")
endif()