# based on tensorflow absl
message("STARTING tensorflow")
find_package(tensorflow-lite CONFIG)
if(tensorflow-lite_FOUND)
    message("tensorflow-lite FOUND ${tensorflow-lite_LIBRARIES}")
else()
    include(tensorflow-lite)
endif()
if(tensorflow-lite_POPULATED)
    set(tensorflow-lite_LIBRARIES tensorflow-lite CACHE STRING "tensorflow-lite libs")
endif()