"# MediaPipe graph that performs hands tracking on desktop with TensorFlow\n"
"# Lite on CPU.\n"
"# Used in the example in\n"
"# mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu.\n"
"\n"
"# CPU image. (ImageFrame)\n"
"input_stream: \"input_video\"\n"
"input_stream: \"image_data\"\n"
"# CPU image. (ImageFrame)\n"
"output_stream: \"illixr_data\"\n"
"\n"
"# Generates side packet cotaining max number of hands to detect/track.\n"
"node {\n"
"  calculator: \"ConstantSidePacketCalculator\"\n"
"  output_side_packet: \"PACKET:num_hands\"\n"
"  node_options: {\n"
"    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {\n"
"      packet { int_value: 2 }\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"# Detects/tracks hand landmarks.\n"
"node {\n"
"  calculator: \"HandLandmarkTrackingCpu\"\n"
"  input_stream: \"IMAGE:input_video\"\n"
"  input_side_packet: \"NUM_HANDS:num_hands\"\n"
"  output_stream: \"LANDMARKS:landmarks\"\n"
"  output_stream: \"HANDEDNESS:handedness\"\n"
"  output_stream: \"PALM_DETECTIONS:multi_palm_detections\"\n"
"  output_stream: \"HAND_ROIS_FROM_LANDMARKS:multi_hand_rects\"\n"
"  output_stream: \"HAND_ROIS_FROM_PALM_DETECTIONS:multi_palm_rects\"\n"
"}\n"
"\n"
"# Subgraph that renders annotations and overlays them on top of the input\n"
"# images (see hand_renderer_cpu.pbtxt).\n"
"node {\n"
"  calculator: \"HandRendererSubgraph\"\n"
"  input_stream: \"IMAGE:input_video\"\n"
"  input_stream: \"IMAGE_DATA:image_data\"\n"
"  input_stream: \"DETECTIONS:multi_palm_detections\"\n"
"  input_stream: \"LANDMARKS:landmarks\"\n"
"  input_stream: \"HANDEDNESS:handedness\"\n"
"  input_stream: \"NORM_RECTS:0:multi_palm_rects\"\n"
"  input_stream: \"NORM_RECTS:1:multi_hand_rects\"\n"
"  output_stream: \"ILLIXR_DATA:illixr_data\"\n"
"}\n"
